PROJECTROOT  = ../..
CSHAREDDIR   = $(PROJECTROOT)/cshared
PROJECT      = itsut
DEBUG        = yes

bins         = $(PROJECT)
includes       = ..
sources       := itsut.c
packages      := cshared
libs          = $(outdir)/libuppertester.a
deps          = $(outdir)/libuppertester.a

include $(CSHAREDDIR)/common.mk
