PROJECTROOT  = ..
CSHAREDDIR   = $(PROJECTROOT)/cshared
PROJECT      = uppertester
DEBUG        = yes
testdir      = tests

alibs        = $(PROJECT)
solibs       = $(PROJECT)

sources       := uppertester.c
headers       := uppertester.h
packages      := cshared

include $(CSHAREDDIR)/common.mk
