PROJECTROOT  = ..
CSHAREDDIR   = $(PROJECTROOT)/cshared
PROJECT      = uppertester
DEBUG        = yes
testdir      = tests

alibs        = $(PROJECT)
solibs       = $(PROJECT)

sources       := uppertester.c uppertester_cmd.c
headers       := uppertester.h
packages      := cshared

postdirs      := itsut

include $(CSHAREDDIR)/common.mk
