/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_AdhesionSubCauseCode_H_
#define	_AdhesionSubCauseCode_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AdhesionSubCauseCode {
	AdhesionSubCauseCode_unavailable	= 0,
	AdhesionSubCauseCode_heavyFrostOnRoad	= 1,
	AdhesionSubCauseCode_fuelOnRoad	= 2,
	AdhesionSubCauseCode_mudOnRoad	= 3,
	AdhesionSubCauseCode_snowOnRoad	= 4,
	AdhesionSubCauseCode_iceOnRoad	= 5,
	AdhesionSubCauseCode_blackIceOnRoad	= 6,
	AdhesionSubCauseCode_oilOnRoad	= 7,
	AdhesionSubCauseCode_looseChippings	= 8,
	AdhesionSubCauseCode_instantBlackIce	= 9,
	AdhesionSubCauseCode_roadsSalted	= 10,
	AdhesionSubCauseCode_flooding	= 11,
	AdhesionSubCauseCode_waterOnRoad	= 12
} e_AdhesionSubCauseCode;

/* AdhesionSubCauseCode */
typedef long	 AdhesionSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AdhesionSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AdhesionSubCauseCode;
asn_struct_free_f AdhesionSubCauseCode_free;
asn_constr_check_f AdhesionSubCauseCode_constraint;
xer_type_decoder_f AdhesionSubCauseCode_decode_xer;
xer_type_encoder_f AdhesionSubCauseCode_encode_xer;
per_type_decoder_f AdhesionSubCauseCode_decode_uper;
per_type_encoder_f AdhesionSubCauseCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AdhesionSubCauseCode_H_ */
#include <asn_internal.h>
