/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/ITS-Container.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -pdu=CAM -pdu=DENM`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_H_
#define	_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode {
	AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_unavailable	= 0,
	AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_strongWinds	= 1,
	AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_damagingHail	= 2,
	AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_hurricane	= 3,
	AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_thunderstorm	= 4,
	AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_tornado	= 5,
	AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_blizzard	= 6
} e_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode;

/* AdverseWeatherCondition-ExtremeWeatherConditionSubCauseCode */
typedef long	 AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode;
asn_struct_free_f AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_free;
asn_struct_print_f AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_print;
asn_constr_check_f AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_constraint;
ber_type_decoder_f AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_decode_ber;
der_type_encoder_f AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_encode_der;
jer_type_encoder_f AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_encode_jer;
per_type_decoder_f AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_decode_uper;
per_type_encoder_f AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AdverseWeatherCondition_ExtremeWeatherConditionSubCauseCode_H_ */
#include <asn_internal.h>
