/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_AdverseWeatherCondition_WindSubCauseCode_H_
#define	_AdverseWeatherCondition_WindSubCauseCode_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AdverseWeatherCondition_WindSubCauseCode {
	AdverseWeatherCondition_WindSubCauseCode_unavailable	= 0,
	AdverseWeatherCondition_WindSubCauseCode_strongWinds	= 1,
	AdverseWeatherCondition_WindSubCauseCode_damagingHail_deprecated	= 2,
	AdverseWeatherCondition_WindSubCauseCode_hurricane	= 3,
	AdverseWeatherCondition_WindSubCauseCode_thunderstorm	= 4,
	AdverseWeatherCondition_WindSubCauseCode_tornado	= 5,
	AdverseWeatherCondition_WindSubCauseCode_blizzard	= 6
} e_AdverseWeatherCondition_WindSubCauseCode;

/* AdverseWeatherCondition-WindSubCauseCode */
typedef long	 AdverseWeatherCondition_WindSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AdverseWeatherCondition_WindSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AdverseWeatherCondition_WindSubCauseCode;
asn_struct_free_f AdverseWeatherCondition_WindSubCauseCode_free;
asn_constr_check_f AdverseWeatherCondition_WindSubCauseCode_constraint;
xer_type_decoder_f AdverseWeatherCondition_WindSubCauseCode_decode_xer;
xer_type_encoder_f AdverseWeatherCondition_WindSubCauseCode_encode_xer;
per_type_decoder_f AdverseWeatherCondition_WindSubCauseCode_decode_uper;
per_type_encoder_f AdverseWeatherCondition_WindSubCauseCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AdverseWeatherCondition_WindSubCauseCode_H_ */
#include <asn_internal.h>
