/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/ITS-Container.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -pdu=CAM -pdu=DENM`
 */


/* Including external dependencies */
#include "AltitudeValue.h"
#include "AltitudeConfidence.h"
#include <constr_SEQUENCE.h>
#ifndef	_Altitude_H_
#define	_Altitude_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Altitude */
typedef struct Altitude {
	AltitudeValue_t	 altitudeValue;
	AltitudeConfidence_t	 altitudeConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Altitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Altitude;
extern asn_SEQUENCE_specifics_t asn_SPC_Altitude_specs_1;
extern asn_TYPE_member_t asn_MBR_Altitude_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Altitude_H_ */
#include <asn_internal.h>
