/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeEnumerated.h>
#ifndef	_AngularAccelerationConfidence_H_
#define	_AngularAccelerationConfidence_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AngularAccelerationConfidence {
	AngularAccelerationConfidence_degSecSquared_01	= 0,
	AngularAccelerationConfidence_degSecSquared_02	= 1,
	AngularAccelerationConfidence_degSecSquared_05	= 2,
	AngularAccelerationConfidence_degSecSquared_10	= 3,
	AngularAccelerationConfidence_degSecSquared_20	= 4,
	AngularAccelerationConfidence_degSecSquared_50	= 5,
	AngularAccelerationConfidence_outOfRange	= 6,
	AngularAccelerationConfidence_unavailable	= 7
} e_AngularAccelerationConfidence;

/* AngularAccelerationConfidence */
typedef long	 AngularAccelerationConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AngularAccelerationConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AngularAccelerationConfidence;
extern const asn_INTEGER_specifics_t asn_SPC_AngularAccelerationConfidence_specs_1;
asn_struct_free_f AngularAccelerationConfidence_free;
asn_constr_check_f AngularAccelerationConfidence_constraint;
per_type_decoder_f AngularAccelerationConfidence_decode_uper;
per_type_encoder_f AngularAccelerationConfidence_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AngularAccelerationConfidence_H_ */
#include <asn_internal.h>
