/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_BarometricPressure_H_
#define	_BarometricPressure_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BarometricPressure {
	BarometricPressure_outOfRangelower	= 2999,
	BarometricPressure_outOfRangeUpper	= 12001,
	BarometricPressure_unavailable	= 12002
} e_BarometricPressure;

/* BarometricPressure */
typedef long	 BarometricPressure_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BarometricPressure;
asn_struct_free_f BarometricPressure_free;
asn_constr_check_f BarometricPressure_constraint;
ber_type_decoder_f BarometricPressure_decode_ber;
der_type_encoder_f BarometricPressure_encode_der;
per_type_decoder_f BarometricPressure_decode_uper;
per_type_encoder_f BarometricPressure_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BarometricPressure_H_ */
#include <asn_internal.h>
