/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../../asn1c-fillabs/skeletons -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <BIT_STRING.h>
#ifndef	_BrakeControl_H_
#define	_BrakeControl_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BrakeControl {
	BrakeControl_abs	= 0,
	BrakeControl_tcs	= 1,
	BrakeControl_esc	= 2
} e_BrakeControl;

/* BrakeControl */
typedef BIT_STRING_t	 BrakeControl_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_BrakeControl_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_BrakeControl;
asn_struct_free_f BrakeControl_free;
asn_constr_check_f BrakeControl_constraint;
per_type_decoder_f BrakeControl_decode_uper;
per_type_encoder_f BrakeControl_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BrakeControl_H_ */
#include <asn_internal.h>
