/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_CartesianAngularAccelerationComponentValue_H_
#define	_CartesianAngularAccelerationComponentValue_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CartesianAngularAccelerationComponentValue {
	CartesianAngularAccelerationComponentValue_negativeOutOfRange	= -255,
	CartesianAngularAccelerationComponentValue_positiveOutOfRange	= 255,
	CartesianAngularAccelerationComponentValue_unavailable	= 256
} e_CartesianAngularAccelerationComponentValue;

/* CartesianAngularAccelerationComponentValue */
typedef long	 CartesianAngularAccelerationComponentValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CartesianAngularAccelerationComponentValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CartesianAngularAccelerationComponentValue;
asn_struct_free_f CartesianAngularAccelerationComponentValue_free;
asn_constr_check_f CartesianAngularAccelerationComponentValue_constraint;
per_type_decoder_f CartesianAngularAccelerationComponentValue_decode_uper;
per_type_encoder_f CartesianAngularAccelerationComponentValue_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CartesianAngularAccelerationComponentValue_H_ */
#include <asn_internal.h>
