/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_CartesianCoordinateSmall_H_
#define	_CartesianCoordinateSmall_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CartesianCoordinateSmall {
	CartesianCoordinateSmall_negativeOutOfRange	= -3094,
	CartesianCoordinateSmall_positiveOutOfRange	= 1001
} e_CartesianCoordinateSmall;

/* CartesianCoordinateSmall */
typedef long	 CartesianCoordinateSmall_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CartesianCoordinateSmall_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CartesianCoordinateSmall;
asn_struct_free_f CartesianCoordinateSmall_free;
asn_constr_check_f CartesianCoordinateSmall_constraint;
ber_type_decoder_f CartesianCoordinateSmall_decode_ber;
der_type_encoder_f CartesianCoordinateSmall_encode_der;
per_type_decoder_f CartesianCoordinateSmall_decode_uper;
per_type_encoder_f CartesianCoordinateSmall_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CartesianCoordinateSmall_H_ */
#include <asn_internal.h>
