/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_ClusterBreakupReason_H_
#define	_ClusterBreakupReason_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ClusterBreakupReason {
	ClusterBreakupReason_notProvided	= 0,
	ClusterBreakupReason_clusteringPurposeCompleted	= 1,
	ClusterBreakupReason_leaderMovedOutOfClusterBoundingBox	= 2,
	ClusterBreakupReason_joiningAnotherCluster	= 3,
	ClusterBreakupReason_enteringLowRiskAreaBasedOnMaps	= 4,
	ClusterBreakupReason_receptionOfCpmContainingCluster	= 5
} e_ClusterBreakupReason;

/* ClusterBreakupReason */
typedef long	 ClusterBreakupReason_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ClusterBreakupReason_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ClusterBreakupReason;
asn_struct_free_f ClusterBreakupReason_free;
asn_constr_check_f ClusterBreakupReason_constraint;
per_type_decoder_f ClusterBreakupReason_decode_uper;
per_type_encoder_f ClusterBreakupReason_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ClusterBreakupReason_H_ */
#include <asn_internal.h>
