/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_ClusterLeaveReason_H_
#define	_ClusterLeaveReason_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ClusterLeaveReason {
	ClusterLeaveReason_notProvided	= 0,
	ClusterLeaveReason_clusterLeaderLost	= 1,
	ClusterLeaveReason_clusterDisbandedByLeader	= 2,
	ClusterLeaveReason_outOfClusterBoundingBox	= 3,
	ClusterLeaveReason_outOfClusterSpeedRange	= 4,
	ClusterLeaveReason_joiningAnotherCluster	= 5,
	ClusterLeaveReason_cancelledJoin	= 6,
	ClusterLeaveReason_failedJoin	= 7,
	ClusterLeaveReason_safetyCondition	= 8
} e_ClusterLeaveReason;

/* ClusterLeaveReason */
typedef long	 ClusterLeaveReason_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ClusterLeaveReason_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ClusterLeaveReason;
asn_struct_free_f ClusterLeaveReason_free;
asn_constr_check_f ClusterLeaveReason_constraint;
per_type_decoder_f ClusterLeaveReason_decode_uper;
per_type_encoder_f ClusterLeaveReason_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ClusterLeaveReason_H_ */
#include <asn_internal.h>
