/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_CollisionRiskSubCauseCode_H_
#define	_CollisionRiskSubCauseCode_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CollisionRiskSubCauseCode {
	CollisionRiskSubCauseCode_unavailable	= 0,
	CollisionRiskSubCauseCode_longitudinalCollisionRisk	= 1,
	CollisionRiskSubCauseCode_crossingCollisionRisk	= 2,
	CollisionRiskSubCauseCode_lateralCollisionRisk	= 3,
	CollisionRiskSubCauseCode_vulnerableRoadUser	= 4,
	CollisionRiskSubCauseCode_collisionRiskWithPedestrian	= 5,
	CollisionRiskSubCauseCode_collisionRiskWithCyclist	= 6,
	CollisionRiskSubCauseCode_collisionRiskWithMotorVehicle	= 7
} e_CollisionRiskSubCauseCode;

/* CollisionRiskSubCauseCode */
typedef long	 CollisionRiskSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CollisionRiskSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CollisionRiskSubCauseCode;
asn_struct_free_f CollisionRiskSubCauseCode_free;
asn_constr_check_f CollisionRiskSubCauseCode_constraint;
per_type_decoder_f CollisionRiskSubCauseCode_decode_uper;
per_type_encoder_f CollisionRiskSubCauseCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CollisionRiskSubCauseCode_H_ */
#include <asn_internal.h>
