/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "asn1/CPM-PDU-Descriptions.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_CpmContainerId_H_
#define	_CpmContainerId_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CpmContainerId */
typedef long	 CpmContainerId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CpmContainerId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CpmContainerId;
asn_struct_free_f CpmContainerId_free;
asn_constr_check_f CpmContainerId_constraint;
per_type_decoder_f CpmContainerId_decode_uper;
per_type_encoder_f CpmContainerId_encode_uper;
#define CpmContainerId_originatingVehicleContainer	((CpmContainerId_t)1)
#define CpmContainerId_originatingRsuContainer	((CpmContainerId_t)2)
#define CpmContainerId_sensorInformationContainer	((CpmContainerId_t)3)
#define CpmContainerId_perceptionRegionContainer	((CpmContainerId_t)4)
#define CpmContainerId_perceivedObjectContainer	((CpmContainerId_t)5)

#ifdef __cplusplus
}
#endif

#endif	/* _CpmContainerId_H_ */
#include <asn_internal.h>
