/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ASN1C-DATE"
 * 	found in "../../asn1c-fillabs/skeletons/standard-modules/date.asn1"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -pdu=CAM -pdu=DENM`
 */


/* Including external dependencies */
#include "YEAR-ENCODING.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#ifndef	_DATE_ENCODING_H_
#define	_DATE_ENCODING_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DATE-ENCODING */
typedef struct DATE_ENCODING {
	YEAR_ENCODING_t	 year;
	long	 month;
	long	 day;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DATE_ENCODING_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DATE_ENCODING;
extern asn_SEQUENCE_specifics_t asn_SPC_DATE_ENCODING_specs_1;
extern asn_TYPE_member_t asn_MBR_DATE_ENCODING_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _DATE_ENCODING_H_ */
#include <asn_internal.h>
