/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "asn1/DENM-PDU-Descriptions.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -pdu=CAM -pdu=DENM`
 */


/* Including external dependencies */
#include "ItsPduHeader.h"
#include "DecentralizedEnvironmentalNotificationMessage.h"
#include <constr_SEQUENCE.h>
#ifndef	_DENM_H_
#define	_DENM_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DENM */
typedef struct DENM {
	ItsPduHeader_t	 header;
	DecentralizedEnvironmentalNotificationMessage_t	 denm;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DENM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DENM;

#ifdef __cplusplus
}
#endif

#endif	/* _DENM_H_ */
#include <asn_internal.h>
