/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../../asn1c-fillabs/skeletons -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeEnumerated.h>
#ifndef	_EuVehicleCategoryL_H_
#define	_EuVehicleCategoryL_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EuVehicleCategoryL {
	EuVehicleCategoryL_l1	= 0,
	EuVehicleCategoryL_l2	= 1,
	EuVehicleCategoryL_l3	= 2,
	EuVehicleCategoryL_l4	= 3,
	EuVehicleCategoryL_l5	= 4,
	EuVehicleCategoryL_l6	= 5,
	EuVehicleCategoryL_l7	= 6
} e_EuVehicleCategoryL;

/* EuVehicleCategoryL */
typedef long	 EuVehicleCategoryL_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EuVehicleCategoryL_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EuVehicleCategoryL;
extern const asn_INTEGER_specifics_t asn_SPC_EuVehicleCategoryL_specs_1;
asn_struct_free_f EuVehicleCategoryL_free;
asn_constr_check_f EuVehicleCategoryL_constraint;
per_type_decoder_f EuVehicleCategoryL_decode_uper;
per_type_encoder_f EuVehicleCategoryL_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EuVehicleCategoryL_H_ */
#include <asn_internal.h>
