/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "asn1/CAM-PDU-Descriptions.asn"
 * 	`asn1c -S ../../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_ExtensionContainerId_H_
#define	_ExtensionContainerId_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExtensionContainerId */
typedef long	 ExtensionContainerId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ExtensionContainerId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ExtensionContainerId;
asn_struct_free_f ExtensionContainerId_free;
asn_constr_check_f ExtensionContainerId_constraint;
ber_type_decoder_f ExtensionContainerId_decode_ber;
der_type_encoder_f ExtensionContainerId_encode_der;
per_type_decoder_f ExtensionContainerId_decode_uper;
per_type_encoder_f ExtensionContainerId_encode_uper;
#define ExtensionContainerId_twoWheelerContainer	((ExtensionContainerId_t)1)
#define ExtensionContainerId_eHorizonLocationSharingContainer	((ExtensionContainerId_t)2)
#define ExtensionContainerId_veryLowFrequencyContainer	((ExtensionContainerId_t)3)
#define ExtensionContainerId_pathPredictionContainer	((ExtensionContainerId_t)4)
#define ExtensionContainerId_generalizedLanePositionsContainer	((ExtensionContainerId_t)5)
#define ExtensionContainerId_vehicleMovementControlContainer	((ExtensionContainerId_t)6)

#ifdef __cplusplus
}
#endif

#endif	/* _ExtensionContainerId_H_ */
#include <asn_internal.h>
