/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "asn1/CAM-PDU-Descriptions.asn"
 * 	`asn1c -S ../../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM`
 */


/* Including external dependencies */
#include "GeneralizedLanePositions.h"
#ifndef	_GeneralizedLanePositionsContainer_H_
#define	_GeneralizedLanePositionsContainer_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GeneralizedLanePositionsContainer */
typedef GeneralizedLanePositions_t	 GeneralizedLanePositionsContainer_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_GeneralizedLanePositionsContainer_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_GeneralizedLanePositionsContainer;
asn_struct_free_f GeneralizedLanePositionsContainer_free;
asn_constr_check_f GeneralizedLanePositionsContainer_constraint;
ber_type_decoder_f GeneralizedLanePositionsContainer_decode_ber;
der_type_encoder_f GeneralizedLanePositionsContainer_encode_der;
per_type_decoder_f GeneralizedLanePositionsContainer_decode_uper;
per_type_encoder_f GeneralizedLanePositionsContainer_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _GeneralizedLanePositionsContainer_H_ */
#include <asn_internal.h>
