/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/ITS-Container.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -pdu=CAM -pdu=DENM`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_HazardousLocation_SurfaceConditionSubCauseCode_H_
#define	_HazardousLocation_SurfaceConditionSubCauseCode_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HazardousLocation_SurfaceConditionSubCauseCode {
	HazardousLocation_SurfaceConditionSubCauseCode_unavailable	= 0,
	HazardousLocation_SurfaceConditionSubCauseCode_rockfalls	= 1,
	HazardousLocation_SurfaceConditionSubCauseCode_earthquakeDamage	= 2,
	HazardousLocation_SurfaceConditionSubCauseCode_sewerCollapse	= 3,
	HazardousLocation_SurfaceConditionSubCauseCode_subsidence	= 4,
	HazardousLocation_SurfaceConditionSubCauseCode_snowDrifts	= 5,
	HazardousLocation_SurfaceConditionSubCauseCode_stormDamage	= 6,
	HazardousLocation_SurfaceConditionSubCauseCode_burstPipe	= 7,
	HazardousLocation_SurfaceConditionSubCauseCode_volcanoEruption	= 8,
	HazardousLocation_SurfaceConditionSubCauseCode_fallingIce	= 9
} e_HazardousLocation_SurfaceConditionSubCauseCode;

/* HazardousLocation-SurfaceConditionSubCauseCode */
typedef long	 HazardousLocation_SurfaceConditionSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HazardousLocation_SurfaceConditionSubCauseCode;
asn_struct_free_f HazardousLocation_SurfaceConditionSubCauseCode_free;
asn_struct_print_f HazardousLocation_SurfaceConditionSubCauseCode_print;
asn_constr_check_f HazardousLocation_SurfaceConditionSubCauseCode_constraint;
ber_type_decoder_f HazardousLocation_SurfaceConditionSubCauseCode_decode_ber;
der_type_encoder_f HazardousLocation_SurfaceConditionSubCauseCode_encode_der;
jer_type_encoder_f HazardousLocation_SurfaceConditionSubCauseCode_encode_jer;
per_type_decoder_f HazardousLocation_SurfaceConditionSubCauseCode_decode_uper;
per_type_encoder_f HazardousLocation_SurfaceConditionSubCauseCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HazardousLocation_SurfaceConditionSubCauseCode_H_ */
#include <asn_internal.h>
