/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../../asn1c-fillabs/skeletons -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_HazardousLocation_ObstacleOnTheRoadSubCauseCode_H_
#define	_HazardousLocation_ObstacleOnTheRoadSubCauseCode_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HazardousLocation_ObstacleOnTheRoadSubCauseCode {
	HazardousLocation_ObstacleOnTheRoadSubCauseCode_unavailable	= 0,
	HazardousLocation_ObstacleOnTheRoadSubCauseCode_shedLoad	= 1,
	HazardousLocation_ObstacleOnTheRoadSubCauseCode_partsOfVehicles	= 2,
	HazardousLocation_ObstacleOnTheRoadSubCauseCode_partsOfTyres	= 3,
	HazardousLocation_ObstacleOnTheRoadSubCauseCode_bigObjects	= 4,
	HazardousLocation_ObstacleOnTheRoadSubCauseCode_fallenTrees	= 5,
	HazardousLocation_ObstacleOnTheRoadSubCauseCode_hubCaps	= 6,
	HazardousLocation_ObstacleOnTheRoadSubCauseCode_waitingVehicles	= 7
} e_HazardousLocation_ObstacleOnTheRoadSubCauseCode;

/* HazardousLocation-ObstacleOnTheRoadSubCauseCode */
typedef long	 HazardousLocation_ObstacleOnTheRoadSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_HazardousLocation_ObstacleOnTheRoadSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_HazardousLocation_ObstacleOnTheRoadSubCauseCode;
asn_struct_free_f HazardousLocation_ObstacleOnTheRoadSubCauseCode_free;
asn_constr_check_f HazardousLocation_ObstacleOnTheRoadSubCauseCode_constraint;
per_type_decoder_f HazardousLocation_ObstacleOnTheRoadSubCauseCode_decode_uper;
per_type_encoder_f HazardousLocation_ObstacleOnTheRoadSubCauseCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HazardousLocation_ObstacleOnTheRoadSubCauseCode_H_ */
#include <asn_internal.h>
