/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_HumanPresenceOnTheRoadSubCauseCode_H_
#define	_HumanPresenceOnTheRoadSubCauseCode_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HumanPresenceOnTheRoadSubCauseCode {
	HumanPresenceOnTheRoadSubCauseCode_unavailable	= 0,
	HumanPresenceOnTheRoadSubCauseCode_childrenOnRoadway	= 1,
	HumanPresenceOnTheRoadSubCauseCode_cyclistOnRoadway	= 2,
	HumanPresenceOnTheRoadSubCauseCode_motorcyclistOnRoadway	= 3,
	HumanPresenceOnTheRoadSubCauseCode_pedestrian	= 4,
	HumanPresenceOnTheRoadSubCauseCode_ordinary_pedestrian	= 5,
	HumanPresenceOnTheRoadSubCauseCode_road_worker	= 6,
	HumanPresenceOnTheRoadSubCauseCode_first_responder	= 7,
	HumanPresenceOnTheRoadSubCauseCode_lightVruVehicle	= 8,
	HumanPresenceOnTheRoadSubCauseCode_bicyclist	= 9,
	HumanPresenceOnTheRoadSubCauseCode_wheelchair_user	= 10,
	HumanPresenceOnTheRoadSubCauseCode_horse_and_rider	= 11,
	HumanPresenceOnTheRoadSubCauseCode_rollerskater	= 12,
	HumanPresenceOnTheRoadSubCauseCode_e_scooter	= 13,
	HumanPresenceOnTheRoadSubCauseCode_personal_transporter	= 14,
	HumanPresenceOnTheRoadSubCauseCode_pedelec	= 15,
	HumanPresenceOnTheRoadSubCauseCode_speed_pedelec	= 16,
	HumanPresenceOnTheRoadSubCauseCode_ptw	= 17,
	HumanPresenceOnTheRoadSubCauseCode_moped	= 18,
	HumanPresenceOnTheRoadSubCauseCode_motorcycle	= 19,
	HumanPresenceOnTheRoadSubCauseCode_motorcycle_and_sidecar_right	= 20,
	HumanPresenceOnTheRoadSubCauseCode_motorcycle_and_sidecar_left	= 21
} e_HumanPresenceOnTheRoadSubCauseCode;

/* HumanPresenceOnTheRoadSubCauseCode */
typedef long	 HumanPresenceOnTheRoadSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_HumanPresenceOnTheRoadSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_HumanPresenceOnTheRoadSubCauseCode;
asn_struct_free_f HumanPresenceOnTheRoadSubCauseCode_free;
asn_constr_check_f HumanPresenceOnTheRoadSubCauseCode_constraint;
ber_type_decoder_f HumanPresenceOnTheRoadSubCauseCode_decode_ber;
der_type_encoder_f HumanPresenceOnTheRoadSubCauseCode_encode_der;
per_type_decoder_f HumanPresenceOnTheRoadSubCauseCode_decode_uper;
per_type_encoder_f HumanPresenceOnTheRoadSubCauseCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HumanPresenceOnTheRoadSubCauseCode_H_ */
#include <asn_internal.h>
