/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/ITS-Container.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -pdu=CAM -pdu=DENM`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_Latitude_H_
#define	_Latitude_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Latitude {
	Latitude_oneMicrodegreeNorth	= 10,
	Latitude_oneMicrodegreeSouth	= -10,
	Latitude_unavailable	= 900000001
} e_Latitude;

/* Latitude */
typedef long	 Latitude_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Latitude_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Latitude;
asn_struct_free_f Latitude_free;
asn_struct_print_f Latitude_print;
asn_constr_check_f Latitude_constraint;
ber_type_decoder_f Latitude_decode_ber;
der_type_encoder_f Latitude_encode_der;
jer_type_encoder_f Latitude_encode_jer;
per_type_decoder_f Latitude_decode_uper;
per_type_encoder_f Latitude_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Latitude_H_ */
#include <asn_internal.h>
