/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM`
 */


/* Including external dependencies */
#include <BIT_STRING.h>
#ifndef	_MatrixIncludedComponents_H_
#define	_MatrixIncludedComponents_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MatrixIncludedComponents {
	MatrixIncludedComponents_xPosition	= 0,
	MatrixIncludedComponents_yPosition	= 1,
	MatrixIncludedComponents_zPosition	= 2,
	MatrixIncludedComponents_xVelocityOrVelocityMagnitude	= 3,
	MatrixIncludedComponents_yVelocityOrVelocityDirection	= 4,
	MatrixIncludedComponents_zSpeed	= 5,
	MatrixIncludedComponents_xAccelOrAccelMagnitude	= 6,
	MatrixIncludedComponents_yAccelOrAccelDirection	= 7,
	MatrixIncludedComponents_zAcceleration	= 8,
	MatrixIncludedComponents_zAngle	= 9,
	MatrixIncludedComponents_yAngle	= 10,
	MatrixIncludedComponents_xAngle	= 11,
	MatrixIncludedComponents_zAngularVelocity	= 12
} e_MatrixIncludedComponents;

/* MatrixIncludedComponents */
typedef BIT_STRING_t	 MatrixIncludedComponents_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MatrixIncludedComponents_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MatrixIncludedComponents;
asn_struct_free_f MatrixIncludedComponents_free;
asn_constr_check_f MatrixIncludedComponents_constraint;
ber_type_decoder_f MatrixIncludedComponents_decode_ber;
der_type_encoder_f MatrixIncludedComponents_encode_der;
per_type_decoder_f MatrixIncludedComponents_decode_uper;
per_type_encoder_f MatrixIncludedComponents_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MatrixIncludedComponents_H_ */
#include <asn_internal.h>
