/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeEnumerated.h>
#ifndef	_MultiplicativeFactor_H_
#define	_MultiplicativeFactor_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MultiplicativeFactor {
	MultiplicativeFactor_tenth	= 0,
	MultiplicativeFactor_half	= 1,
	MultiplicativeFactor_two	= 2,
	MultiplicativeFactor_three	= 3,
	MultiplicativeFactor_five	= 4,
	MultiplicativeFactor_ten	= 5,
	MultiplicativeFactor_fifty	= 6,
	MultiplicativeFactor_hundred	= 7
	/*
	 * Enumeration is extensible
	 */
} e_MultiplicativeFactor;

/* MultiplicativeFactor */
typedef long	 MultiplicativeFactor_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MultiplicativeFactor_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MultiplicativeFactor;
extern const asn_INTEGER_specifics_t asn_SPC_MultiplicativeFactor_specs_1;
asn_struct_free_f MultiplicativeFactor_free;
asn_constr_check_f MultiplicativeFactor_constraint;
xer_type_decoder_f MultiplicativeFactor_decode_xer;
xer_type_encoder_f MultiplicativeFactor_encode_xer;
per_type_decoder_f MultiplicativeFactor_decode_uper;
per_type_encoder_f MultiplicativeFactor_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MultiplicativeFactor_H_ */
#include <asn_internal.h>
