/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <UTF8String.h>
#ifndef	_OpeningDaysHours_H_
#define	_OpeningDaysHours_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OpeningDaysHours */
typedef UTF8String_t	 OpeningDaysHours_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OpeningDaysHours;
asn_struct_free_f OpeningDaysHours_free;
asn_constr_check_f OpeningDaysHours_constraint;
xer_type_decoder_f OpeningDaysHours_decode_xer;
xer_type_encoder_f OpeningDaysHours_encode_xer;
per_type_decoder_f OpeningDaysHours_decode_uper;
per_type_encoder_f OpeningDaysHours_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _OpeningDaysHours_H_ */
#include <asn_internal.h>
