/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_ParkingReservationType_H_
#define	_ParkingReservationType_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ParkingReservationType {
	ParkingReservationType_disabled	= 0,
	ParkingReservationType_pregnant	= 1,
	ParkingReservationType_womenOnly	= 2,
	ParkingReservationType_parentAndChild	= 3,
	ParkingReservationType_loadAndOffloadGoods	= 4,
	ParkingReservationType_manualElectricVehicleCharging	= 5,
	ParkingReservationType_automatedElectricVehicleCharging	= 6,
	ParkingReservationType_refriferatedTransport	= 7,
	ParkingReservationType_vip	= 8,
	ParkingReservationType_preBooking	= 9,
	ParkingReservationType_freeToBeReserved	= 10,
	ParkingReservationType_reservationNotPossible	= 11,
	ParkingReservationType_automatedValetparking	= 12,
	ParkingReservationType_permit	= 13,
	ParkingReservationType_unmarked	= 14
} e_ParkingReservationType;

/* ParkingReservationType */
typedef long	 ParkingReservationType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ParkingReservationType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ParkingReservationType;
asn_struct_free_f ParkingReservationType_free;
asn_constr_check_f ParkingReservationType_constraint;
xer_type_decoder_f ParkingReservationType_decode_xer;
xer_type_encoder_f ParkingReservationType_encode_xer;
per_type_decoder_f ParkingReservationType_decode_uper;
per_type_encoder_f ParkingReservationType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ParkingReservationType_H_ */
#include <asn_internal.h>
