/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_ParkingAreaArrangementType_H_
#define	_ParkingAreaArrangementType_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ParkingAreaArrangementType {
	ParkingAreaArrangementType_parallelParkingSpace	= 0,
	ParkingAreaArrangementType_diagonalParkingSpace	= 1,
	ParkingAreaArrangementType_perpendicularParkingSpace	= 2,
	ParkingAreaArrangementType_queueParking	= 3,
	ParkingAreaArrangementType_mixed	= 4,
	ParkingAreaArrangementType_unknown	= 7
} e_ParkingAreaArrangementType;

/* ParkingAreaArrangementType */
typedef long	 ParkingAreaArrangementType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ParkingAreaArrangementType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ParkingAreaArrangementType;
asn_struct_free_f ParkingAreaArrangementType_free;
asn_constr_check_f ParkingAreaArrangementType_constraint;
ber_type_decoder_f ParkingAreaArrangementType_decode_ber;
der_type_encoder_f ParkingAreaArrangementType_encode_der;
per_type_decoder_f ParkingAreaArrangementType_decode_uper;
per_type_encoder_f ParkingAreaArrangementType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ParkingAreaArrangementType_H_ */
#include <asn_internal.h>
