/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include "Identifier2B.h"
#include "ParkingSpaceStatus.h"
#include <constr_SEQUENCE.h>
#ifndef	_ParkingSpaceBasic_H_
#define	_ParkingSpaceBasic_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DeltaReferencePosition;

/* ParkingSpaceBasic */
typedef struct ParkingSpaceBasic {
	Identifier2B_t	 id;
	struct DeltaReferencePosition	*location;	/* OPTIONAL */
	ParkingSpaceStatus_t	 status;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ParkingSpaceBasic_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParkingSpaceBasic;
extern asn_SEQUENCE_specifics_t asn_SPC_ParkingSpaceBasic_specs_1;
extern asn_TYPE_member_t asn_MBR_ParkingSpaceBasic_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DeltaReferencePosition.h"

#endif	/* _ParkingSpaceBasic_H_ */
#include <asn_internal.h>
