/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM`
 */


/* Including external dependencies */
#include <NULL.h>
#include <NativeInteger.h>
#include "TimestampIts.h"
#include <constr_CHOICE.h>
#ifndef	_ParkingOccupancyInfo_H_
#define	_ParkingOccupancyInfo_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ParkingOccupancyInfo_PR {
	ParkingOccupancyInfo_PR_NOTHING,	/* No components present */
	ParkingOccupancyInfo_PR_unknown,
	ParkingOccupancyInfo_PR_unlimitedOccupancy,
	ParkingOccupancyInfo_PR_onlyWhileCharging,
	ParkingOccupancyInfo_PR_limitedDuration,
	ParkingOccupancyInfo_PR_onlyWhileChargingLimitedDuration,
	ParkingOccupancyInfo_PR_parkingAllowedUntil,
	ParkingOccupancyInfo_PR_forcedParkingUntil
	/* Extensions may appear below */
	
} ParkingOccupancyInfo_PR;

/* ParkingOccupancyInfo */
typedef struct ParkingOccupancyInfo {
	ParkingOccupancyInfo_PR present;
	union ParkingOccupancyInfo_u {
		NULL_t	 unknown;
		NULL_t	 unlimitedOccupancy;
		NULL_t	 onlyWhileCharging;
		long	 limitedDuration;
		long	 onlyWhileChargingLimitedDuration;
		TimestampIts_t	 parkingAllowedUntil;
		TimestampIts_t	 forcedParkingUntil;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ParkingOccupancyInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParkingOccupancyInfo;
extern asn_CHOICE_specifics_t asn_SPC_ParkingOccupancyInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_ParkingOccupancyInfo_1[7];
extern asn_per_constraints_t asn_PER_type_ParkingOccupancyInfo_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ParkingOccupancyInfo_H_ */
#include <asn_internal.h>
