/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include "DeltaTimeTenthOfSecond.h"
#include "DeltaTimeTenSeconds.h"
#include "DeltaTimeSecond.h"
#include <constr_CHOICE.h>
#ifndef	_PathDeltaTimeChoice_H_
#define	_PathDeltaTimeChoice_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PathDeltaTimeChoice_PR {
	PathDeltaTimeChoice_PR_NOTHING,	/* No components present */
	PathDeltaTimeChoice_PR_deltaTimeHighPrecision,
	PathDeltaTimeChoice_PR_deltaTimeBigRange,
	/* Extensions may appear below */
	PathDeltaTimeChoice_PR_deltaTimeMidRange
} PathDeltaTimeChoice_PR;

/* PathDeltaTimeChoice */
typedef struct PathDeltaTimeChoice {
	PathDeltaTimeChoice_PR present;
	union PathDeltaTimeChoice_u {
		DeltaTimeTenthOfSecond_t	 deltaTimeHighPrecision;
		DeltaTimeTenSeconds_t	 deltaTimeBigRange;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		DeltaTimeSecond_t	 deltaTimeMidRange;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PathDeltaTimeChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PathDeltaTimeChoice;
extern asn_CHOICE_specifics_t asn_SPC_PathDeltaTimeChoice_specs_1;
extern asn_TYPE_member_t asn_MBR_PathDeltaTimeChoice_1[3];
extern asn_per_constraints_t asn_PER_type_PathDeltaTimeChoice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PathDeltaTimeChoice_H_ */
#include <asn_internal.h>
