/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "asn1/CAM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include "PathPredictedList.h"
#include <constr_SEQUENCE.h>
#ifndef	_PathPredictionContainer_H_
#define	_PathPredictionContainer_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PathPredictionContainer */
typedef struct PathPredictionContainer {
	PathPredictedList_t	 pathPredictedList;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PathPredictionContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PathPredictionContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_PathPredictionContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_PathPredictionContainer_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _PathPredictionContainer_H_ */
#include <asn_internal.h>
