/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Description"
 * 	found in "asn1/DENM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <BOOLEAN.h>
#ifndef	_PerceivedEvent_H_
#define	_PerceivedEvent_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PerceivedEvent */
typedef BOOLEAN_t	 PerceivedEvent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PerceivedEvent;
asn_struct_free_f PerceivedEvent_free;
asn_constr_check_f PerceivedEvent_constraint;
xer_type_decoder_f PerceivedEvent_decode_xer;
xer_type_encoder_f PerceivedEvent_encode_xer;
per_type_decoder_f PerceivedEvent_decode_uper;
per_type_encoder_f PerceivedEvent_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PerceivedEvent_H_ */
#include <asn_internal.h>
