/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/ITS-Container.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -pdu=CAM -pdu=DENM`
 */


/* Including external dependencies */
#include <NumericString.h>
#ifndef	_PhoneNumber_H_
#define	_PhoneNumber_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PhoneNumber */
typedef NumericString_t	 PhoneNumber_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PhoneNumber_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PhoneNumber;
asn_struct_free_f PhoneNumber_free;
asn_struct_print_f PhoneNumber_print;
asn_constr_check_f PhoneNumber_constraint;
ber_type_decoder_f PhoneNumber_decode_ber;
der_type_encoder_f PhoneNumber_encode_der;
jer_type_encoder_f PhoneNumber_encode_jer;
per_type_decoder_f PhoneNumber_decode_uper;
per_type_encoder_f PhoneNumber_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PhoneNumber_H_ */
#include <asn_internal.h>
