/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/ITS-Container.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -pdu=CAM -pdu=DENM`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_PostCrashSubCauseCode_H_
#define	_PostCrashSubCauseCode_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PostCrashSubCauseCode {
	PostCrashSubCauseCode_unavailable	= 0,
	PostCrashSubCauseCode_accidentWithoutECallTriggered	= 1,
	PostCrashSubCauseCode_accidentWithECallManuallyTriggered	= 2,
	PostCrashSubCauseCode_accidentWithECallAutomaticallyTriggered	= 3,
	PostCrashSubCauseCode_accidentWithECallTriggeredWithoutAccessToCellularNetwork	= 4
} e_PostCrashSubCauseCode;

/* PostCrashSubCauseCode */
typedef long	 PostCrashSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PostCrashSubCauseCode;
asn_struct_free_f PostCrashSubCauseCode_free;
asn_struct_print_f PostCrashSubCauseCode_print;
asn_constr_check_f PostCrashSubCauseCode_constraint;
ber_type_decoder_f PostCrashSubCauseCode_decode_ber;
der_type_encoder_f PostCrashSubCauseCode_encode_der;
jer_type_encoder_f PostCrashSubCauseCode_encode_jer;
per_type_decoder_f PostCrashSubCauseCode_decode_uper;
per_type_encoder_f PostCrashSubCauseCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PostCrashSubCauseCode_H_ */
#include <asn_internal.h>
