/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_PrecipitationIntensity_H_
#define	_PrecipitationIntensity_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PrecipitationIntensity {
	PrecipitationIntensity_outOfRange	= 2000,
	PrecipitationIntensity_unavailable	= 2001
} e_PrecipitationIntensity;

/* PrecipitationIntensity */
typedef long	 PrecipitationIntensity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrecipitationIntensity;
asn_struct_free_f PrecipitationIntensity_free;
asn_constr_check_f PrecipitationIntensity_constraint;
xer_type_decoder_f PrecipitationIntensity_decode_xer;
xer_type_encoder_f PrecipitationIntensity_encode_xer;
per_type_decoder_f PrecipitationIntensity_decode_uper;
per_type_encoder_f PrecipitationIntensity_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PrecipitationIntensity_H_ */
#include <asn_internal.h>
