/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/ITS-Container.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -pdu=CAM -pdu=DENM`
 */


/* Including external dependencies */
#include "ProtectedZoneType.h"
#include "TimestampIts.h"
#include "Latitude.h"
#include "Longitude.h"
#include "ProtectedZoneRadius.h"
#include "ProtectedZoneID.h"
#include <constr_SEQUENCE.h>
#ifndef	_ProtectedCommunicationZone_H_
#define	_ProtectedCommunicationZone_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProtectedCommunicationZone */
typedef struct ProtectedCommunicationZone {
	ProtectedZoneType_t	 protectedZoneType;
	TimestampIts_t	*expiryTime;	/* OPTIONAL */
	Latitude_t	 protectedZoneLatitude;
	Longitude_t	 protectedZoneLongitude;
	ProtectedZoneRadius_t	*protectedZoneRadius;	/* OPTIONAL */
	ProtectedZoneID_t	*protectedZoneID;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtectedCommunicationZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtectedCommunicationZone;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtectedCommunicationZone_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtectedCommunicationZone_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _ProtectedCommunicationZone_H_ */
#include <asn_internal.h>
