/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_RailwayLevelCrossingSubCauseCode_H_
#define	_RailwayLevelCrossingSubCauseCode_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RailwayLevelCrossingSubCauseCode {
	RailwayLevelCrossingSubCauseCode_unavailable	= 0,
	RailwayLevelCrossingSubCauseCode_doNotCrossAbnormalSituation	= 1,
	RailwayLevelCrossingSubCauseCode_closed	= 2,
	RailwayLevelCrossingSubCauseCode_unguarded	= 3,
	RailwayLevelCrossingSubCauseCode_nominal	= 4,
	RailwayLevelCrossingSubCauseCode_trainApproaching	= 5
} e_RailwayLevelCrossingSubCauseCode;

/* RailwayLevelCrossingSubCauseCode */
typedef long	 RailwayLevelCrossingSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RailwayLevelCrossingSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RailwayLevelCrossingSubCauseCode;
asn_struct_free_f RailwayLevelCrossingSubCauseCode_free;
asn_constr_check_f RailwayLevelCrossingSubCauseCode_constraint;
per_type_decoder_f RailwayLevelCrossingSubCauseCode_decode_uper;
per_type_encoder_f RailwayLevelCrossingSubCauseCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RailwayLevelCrossingSubCauseCode_H_ */
#include <asn_internal.h>
