/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeEnumerated.h>
#ifndef	_RelevanceDistance_H_
#define	_RelevanceDistance_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RelevanceDistance {
	RelevanceDistance_lessThan50m	= 0,
	RelevanceDistance_lessThan100m	= 1,
	RelevanceDistance_lessThan200m	= 2,
	RelevanceDistance_lessThan500m	= 3,
	RelevanceDistance_lessThan1000m	= 4,
	RelevanceDistance_lessThan5km	= 5,
	RelevanceDistance_lessThan10km	= 6,
	RelevanceDistance_over10km	= 7
} e_RelevanceDistance;

/* RelevanceDistance */
typedef long	 RelevanceDistance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RelevanceDistance;
asn_struct_free_f RelevanceDistance_free;
asn_constr_check_f RelevanceDistance_constraint;
per_type_decoder_f RelevanceDistance_decode_uper;
per_type_encoder_f RelevanceDistance_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RelevanceDistance_H_ */
#include <asn_internal.h>
