/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PerceptionRegionContainer"
 * 	found in "asn1/CPM-PerceptionRegionContainer.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include "Shape.h"
#include <constr_CHOICE.h>
#ifndef	_ReportingType_H_
#define	_ReportingType_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReportingType_PR {
	ReportingType_PR_NOTHING,	/* No components present */
	ReportingType_PR_reportingAllObjects,
	ReportingType_PR_reportingAllNonPermanentObjects
	/* Extensions may appear below */
	
} ReportingType_PR;

/* ReportingType */
typedef struct ReportingType {
	ReportingType_PR present;
	union ReportingType_u {
		Shape_t	 reportingAllObjects;
		Shape_t	 reportingAllNonPermanentObjects;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportingType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportingType;
extern asn_CHOICE_specifics_t asn_SPC_ReportingType_specs_1;
extern asn_TYPE_member_t asn_MBR_ReportingType_1[2];
extern asn_per_constraints_t asn_PER_type_ReportingType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ReportingType_H_ */
#include <asn_internal.h>
