/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_H_
#define	_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode {
	RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_unavailable	= 0,
	RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_emergencyVehicles	= 1,
	RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_rescueHelicopterLanding	= 2,
	RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_policeActivityOngoing	= 3,
	RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_medicalEmergencyOngoing	= 4,
	RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_childAbductionInProgress_deprecated	= 5,
	RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_prioritizedVehicle	= 6,
	RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_rescueAndRecoveryVehicle	= 7
} e_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode;

/* RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode */
typedef long	 RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode;
asn_struct_free_f RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_free;
asn_constr_check_f RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_constraint;
xer_type_decoder_f RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_decode_xer;
xer_type_encoder_f RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_encode_xer;
per_type_decoder_f RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_decode_uper;
per_type_encoder_f RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RescueRecoveryAndMaintenanceWorkInProgressSubCauseCode_H_ */
#include <asn_internal.h>
