/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/ITS-Container.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -pdu=CAM -pdu=DENM`
 */


/* Including external dependencies */
#include <NativeEnumerated.h>
#ifndef	_RoadType_H_
#define	_RoadType_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RoadType {
	RoadType_urban_NoStructuralSeparationToOppositeLanes	= 0,
	RoadType_urban_WithStructuralSeparationToOppositeLanes	= 1,
	RoadType_nonUrban_NoStructuralSeparationToOppositeLanes	= 2,
	RoadType_nonUrban_WithStructuralSeparationToOppositeLanes	= 3
} e_RoadType;

/* RoadType */
typedef long	 RoadType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RoadType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RoadType;
extern const asn_INTEGER_specifics_t asn_SPC_RoadType_specs_1;
asn_struct_free_f RoadType_free;
asn_struct_print_f RoadType_print;
asn_constr_check_f RoadType_constraint;
ber_type_decoder_f RoadType_decode_ber;
der_type_encoder_f RoadType_encode_der;
jer_type_encoder_f RoadType_encode_jer;
per_type_decoder_f RoadType_decode_uper;
per_type_encoder_f RoadType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RoadType_H_ */
#include <asn_internal.h>
