/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Description"
 * 	found in "asn1/DENM-PDU-Descriptions.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM`
 */


/* Including external dependencies */
#include "LightBarSirenInUse.h"
#include "SpeedLimit.h"
#include "TrafficRule.h"
#include <constr_SEQUENCE.h>
#ifndef	_RoadWorksContainerExtended_H_
#define	_RoadWorksContainerExtended_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ClosedLanes;
struct RestrictedTypes;
struct CauseCodeV2;
struct ItineraryPath;
struct DeltaReferencePosition;
struct ActionIdList;

/* RoadWorksContainerExtended */
typedef struct RoadWorksContainerExtended {
	LightBarSirenInUse_t	*lightBarSirenInUse;	/* OPTIONAL */
	struct ClosedLanes	*closedLanes;	/* OPTIONAL */
	struct RestrictedTypes	*restriction;	/* OPTIONAL */
	SpeedLimit_t	*speedLimit;	/* OPTIONAL */
	struct CauseCodeV2	*incidentIndication;	/* OPTIONAL */
	struct ItineraryPath	*recommendedPath;	/* OPTIONAL */
	struct DeltaReferencePosition	*startingPointSpeedLimit;	/* OPTIONAL */
	TrafficRule_t	*trafficFlowRule;	/* OPTIONAL */
	struct ActionIdList	*referenceDenms;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadWorksContainerExtended_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadWorksContainerExtended;
extern asn_SEQUENCE_specifics_t asn_SPC_RoadWorksContainerExtended_specs_1;
extern asn_TYPE_member_t asn_MBR_RoadWorksContainerExtended_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ClosedLanes.h"
#include "RestrictedTypes.h"
#include "CauseCodeV2.h"
#include "ItineraryPath.h"
#include "DeltaReferencePosition.h"
#include "ActionIdList.h"

#endif	/* _RoadWorksContainerExtended_H_ */
#include <asn_internal.h>
