/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Description"
 * 	found in "asn1/DENM-PDU-Descriptions.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM`
 */

#include "RoadConfigurationContainer.h"

asn_TYPE_member_t asn_MBR_RoadConfigurationContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RoadConfigurationContainer, roadConfigurationConfidence),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MetaInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"roadConfigurationConfidence"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RoadConfigurationContainer, roadConfigurationSectionList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RoadConfigurationSectionList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"roadConfigurationSectionList"
		},
};
static const ber_tlv_tag_t asn_DEF_RoadConfigurationContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RoadConfigurationContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* roadConfigurationConfidence */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* roadConfigurationSectionList */
};
asn_SEQUENCE_specifics_t asn_SPC_RoadConfigurationContainer_specs_1 = {
	sizeof(struct RoadConfigurationContainer),
	offsetof(struct RoadConfigurationContainer, _asn_ctx),
	asn_MAP_RoadConfigurationContainer_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RoadConfigurationContainer = {
	"RoadConfigurationContainer",
	"RoadConfigurationContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_RoadConfigurationContainer_tags_1,
	sizeof(asn_DEF_RoadConfigurationContainer_tags_1)
		/sizeof(asn_DEF_RoadConfigurationContainer_tags_1[0]), /* 1 */
	asn_DEF_RoadConfigurationContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_RoadConfigurationContainer_tags_1)
		/sizeof(asn_DEF_RoadConfigurationContainer_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RoadConfigurationContainer_1,
	2,	/* Elements count */
	&asn_SPC_RoadConfigurationContainer_specs_1	/* Additional specs */
};

