/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_SaeAutomationLevel_H_
#define	_SaeAutomationLevel_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SaeAutomationLevel */
typedef long	 SaeAutomationLevel_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SaeAutomationLevel_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SaeAutomationLevel;
asn_struct_free_f SaeAutomationLevel_free;
asn_constr_check_f SaeAutomationLevel_constraint;
per_type_decoder_f SaeAutomationLevel_decode_uper;
per_type_encoder_f SaeAutomationLevel_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SaeAutomationLevel_H_ */
#include <asn_internal.h>
