/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <BOOLEAN.h>
#ifndef	_SafeDistanceIndicator_H_
#define	_SafeDistanceIndicator_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SafeDistanceIndicator */
typedef BOOLEAN_t	 SafeDistanceIndicator_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SafeDistanceIndicator;
asn_struct_free_f SafeDistanceIndicator_free;
asn_constr_check_f SafeDistanceIndicator_constraint;
per_type_decoder_f SafeDistanceIndicator_decode_uper;
per_type_encoder_f SafeDistanceIndicator_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SafeDistanceIndicator_H_ */
#include <asn_internal.h>
