/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "asn1/CAM-PDU-Descriptions.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -pdu=CAM -pdu=DENM`
 */


/* Including external dependencies */
#include "SpecialTransportType.h"
#include "LightBarSirenInUse.h"
#include <constr_SEQUENCE.h>
#ifndef	_SpecialTransportContainer_H_
#define	_SpecialTransportContainer_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SpecialTransportContainer */
typedef struct SpecialTransportContainer {
	SpecialTransportType_t	 specialTransportType;
	LightBarSirenInUse_t	 lightBarSirenInUse;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SpecialTransportContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpecialTransportContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_SpecialTransportContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_SpecialTransportContainer_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SpecialTransportContainer_H_ */
#include <asn_internal.h>
