/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "asn1/DENM-PDU-Descriptions.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -pdu=CAM -pdu=DENM`
 */


/* Including external dependencies */
#include <NativeEnumerated.h>
#ifndef	_Termination_H_
#define	_Termination_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Termination {
	Termination_isCancellation	= 0,
	Termination_isNegation	= 1
} e_Termination;

/* Termination */
typedef long	 Termination_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Termination_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Termination;
extern const asn_INTEGER_specifics_t asn_SPC_Termination_specs_1;
asn_struct_free_f Termination_free;
asn_struct_print_f Termination_print;
asn_constr_check_f Termination_constraint;
ber_type_decoder_f Termination_decode_ber;
der_type_encoder_f Termination_encode_der;
jer_type_encoder_f Termination_encode_jer;
per_type_decoder_f Termination_decode_uper;
per_type_encoder_f Termination_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Termination_H_ */
#include <asn_internal.h>
