/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "asn1/CAM-PDU-Descriptions.asn"
 * 	`asn1c -S ../../../asn1c-fillabs/skeletons -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <constr_SEQUENCE.h>
#ifndef	_TwoWheelerContainer_H_
#define	_TwoWheelerContainer_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TwoWheelerTypeSpecificInformation;
struct CartesianAngle;
struct Wgs84Angle;
struct StabilityChangeIndication;

/* TwoWheelerContainer */
typedef struct TwoWheelerContainer {
	struct TwoWheelerTypeSpecificInformation	*typeSpecificInformation;	/* OPTIONAL */
	struct CartesianAngle	*rollAngle;	/* OPTIONAL */
	struct Wgs84Angle	*orientation;	/* OPTIONAL */
	struct StabilityChangeIndication	*stabilityChangeIndication;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TwoWheelerContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TwoWheelerContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_TwoWheelerContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_TwoWheelerContainer_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TwoWheelerTypeSpecificInformation.h"
#include "CartesianAngle.h"
#include "Wgs84Angle.h"
#include "StabilityChangeIndication.h"

#endif	/* _TwoWheelerContainer_H_ */
#include <asn_internal.h>
