/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeEnumerated.h>
#ifndef	_UsageIndication_H_
#define	_UsageIndication_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UsageIndication {
	UsageIndication_noIndication	= 0,
	UsageIndication_specialUse	= 1,
	UsageIndication_rescueOperation	= 2,
	/*
	 * Enumeration is extensible
	 */
	UsageIndication_railroad	= 3,
	UsageIndication_fixedRoute	= 4,
	UsageIndication_restrictedRoute	= 5,
	UsageIndication_adasAd	= 6,
	UsageIndication_navigation	= 7
} e_UsageIndication;

/* UsageIndication */
typedef long	 UsageIndication_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_UsageIndication_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_UsageIndication;
extern const asn_INTEGER_specifics_t asn_SPC_UsageIndication_specs_1;
asn_struct_free_f UsageIndication_free;
asn_constr_check_f UsageIndication_constraint;
per_type_decoder_f UsageIndication_decode_uper;
per_type_encoder_f UsageIndication_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UsageIndication_H_ */
#include <asn_internal.h>
