/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/VAM-PDU-Descriptions.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM`
 */


/* Including external dependencies */
#include "DeltaTimeQuarterSecond.h"
#include <constr_SEQUENCE.h>
#ifndef	_VruClusterOperationContainer_H_
#define	_VruClusterOperationContainer_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ClusterJoinInfo;
struct ClusterLeaveInfo;
struct ClusterBreakupInfo;

/* VruClusterOperationContainer */
typedef struct VruClusterOperationContainer {
	struct ClusterJoinInfo	*clusterJoinInfo;	/* OPTIONAL */
	struct ClusterLeaveInfo	*clusterLeaveInfo;	/* OPTIONAL */
	struct ClusterBreakupInfo	*clusterBreakupInfo;	/* OPTIONAL */
	DeltaTimeQuarterSecond_t	*clusterIdChangeTimeInfo;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VruClusterOperationContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VruClusterOperationContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_VruClusterOperationContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_VruClusterOperationContainer_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ClusterJoinInfo.h"
#include "ClusterLeaveInfo.h"
#include "ClusterBreakupInfo.h"

#endif	/* _VruClusterOperationContainer_H_ */
#include <asn_internal.h>
