/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_VruSubProfileMotorcyclist_H_
#define	_VruSubProfileMotorcyclist_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VruSubProfileMotorcyclist {
	VruSubProfileMotorcyclist_unavailable	= 0,
	VruSubProfileMotorcyclist_moped	= 1,
	VruSubProfileMotorcyclist_motorcycle	= 2,
	VruSubProfileMotorcyclist_motorcycle_and_sidecar_right	= 3,
	VruSubProfileMotorcyclist_motorcycle_and_sidecar_left	= 4
} e_VruSubProfileMotorcyclist;

/* VruSubProfileMotorcyclist */
typedef long	 VruSubProfileMotorcyclist_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VruSubProfileMotorcyclist_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VruSubProfileMotorcyclist;
asn_struct_free_f VruSubProfileMotorcyclist_free;
asn_constr_check_f VruSubProfileMotorcyclist_constraint;
ber_type_decoder_f VruSubProfileMotorcyclist_decode_ber;
der_type_encoder_f VruSubProfileMotorcyclist_encode_der;
per_type_decoder_f VruSubProfileMotorcyclist_decode_uper;
per_type_encoder_f VruSubProfileMotorcyclist_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VruSubProfileMotorcyclist_H_ */
#include <asn_internal.h>
