/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_VruSizeClass_H_
#define	_VruSizeClass_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VruSizeClass {
	VruSizeClass_unavailable	= 0,
	VruSizeClass_low	= 1,
	VruSizeClass_medium	= 2,
	VruSizeClass_high	= 3
} e_VruSizeClass;

/* VruSizeClass */
typedef long	 VruSizeClass_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VruSizeClass_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VruSizeClass;
asn_struct_free_f VruSizeClass_free;
asn_constr_check_f VruSizeClass_constraint;
xer_type_decoder_f VruSizeClass_decode_xer;
xer_type_encoder_f VruSizeClass_encode_xer;
per_type_decoder_f VruSizeClass_decode_uper;
per_type_encoder_f VruSizeClass_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VruSizeClass_H_ */
#include <asn_internal.h>
