/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -S ../../asn1c-fillabs/skeletons -no-gen-example -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM`
 */


/* Including external dependencies */
#include <BIT_STRING.h>
#ifndef	_VruSpecificExteriorLights_H_
#define	_VruSpecificExteriorLights_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VruSpecificExteriorLights {
	VruSpecificExteriorLights_unavailable	= 0,
	VruSpecificExteriorLights_backFlashLight	= 1,
	VruSpecificExteriorLights_helmetLight	= 2,
	VruSpecificExteriorLights_armLight	= 3,
	VruSpecificExteriorLights_legLight	= 4,
	VruSpecificExteriorLights_wheelLight	= 5
} e_VruSpecificExteriorLights;

/* VruSpecificExteriorLights */
typedef BIT_STRING_t	 VruSpecificExteriorLights_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VruSpecificExteriorLights_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VruSpecificExteriorLights;
asn_struct_free_f VruSpecificExteriorLights_free;
asn_constr_check_f VruSpecificExteriorLights_constraint;
ber_type_decoder_f VruSpecificExteriorLights_decode_ber;
der_type_encoder_f VruSpecificExteriorLights_encode_der;
per_type_decoder_f VruSpecificExteriorLights_decode_uper;
per_type_encoder_f VruSpecificExteriorLights_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VruSpecificExteriorLights_H_ */
#include <asn_internal.h>
