/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_VruSubProfileAnimal_H_
#define	_VruSubProfileAnimal_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VruSubProfileAnimal {
	VruSubProfileAnimal_unavailable	= 0,
	VruSubProfileAnimal_wild_animal	= 1,
	VruSubProfileAnimal_farm_animal	= 2,
	VruSubProfileAnimal_service_animal	= 3
} e_VruSubProfileAnimal;

/* VruSubProfileAnimal */
typedef long	 VruSubProfileAnimal_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VruSubProfileAnimal_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VruSubProfileAnimal;
asn_struct_free_f VruSubProfileAnimal_free;
asn_constr_check_f VruSubProfileAnimal_constraint;
per_type_decoder_f VruSubProfileAnimal_decode_uper;
per_type_encoder_f VruSubProfileAnimal_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VruSubProfileAnimal_H_ */
#include <asn_internal.h>
