/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "asn1/CAM-PDU-Descriptions.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-XER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include "ExtensionContainerId.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "TwoWheelerContainer.h"
#include "EHorizonLocationSharingContainer.h"
#include "VeryLowFrequencyContainer.h"
#include "PathPredictionContainer.h"
#include "GeneralizedLanePositionsContainer.h"
#include "VehicleMovementControlContainer.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#ifndef	_WrappedExtensionContainer_H_
#define	_WrappedExtensionContainer_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum WrappedExtensionContainer__containerData_PR {
	WrappedExtensionContainer__containerData_PR_NOTHING,	/* No components present */
	WrappedExtensionContainer__containerData_PR_TwoWheelerContainer,
	WrappedExtensionContainer__containerData_PR_EHorizonLocationSharingContainer,
	WrappedExtensionContainer__containerData_PR_VeryLowFrequencyContainer,
	WrappedExtensionContainer__containerData_PR_PathPredictionContainer,
	WrappedExtensionContainer__containerData_PR_GeneralizedLanePositionsContainer,
	WrappedExtensionContainer__containerData_PR_VehicleMovementControlContainer
} WrappedExtensionContainer__containerData_PR;

/* WrappedExtensionContainer */
typedef struct WrappedExtensionContainer {
	ExtensionContainerId_t	 containerId;
	struct WrappedExtensionContainer__containerData {
		WrappedExtensionContainer__containerData_PR present;
		union WrappedExtensionContainer__containerData_u {
			TwoWheelerContainer_t	 TwoWheelerContainer;
			EHorizonLocationSharingContainer_t	 EHorizonLocationSharingContainer;
			VeryLowFrequencyContainer_t	 VeryLowFrequencyContainer;
			PathPredictionContainer_t	 PathPredictionContainer;
			GeneralizedLanePositionsContainer_t	 GeneralizedLanePositionsContainer;
			VehicleMovementControlContainer_t	 VehicleMovementControlContainer;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} containerData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WrappedExtensionContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WrappedExtensionContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_WrappedExtensionContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_WrappedExtensionContainer_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _WrappedExtensionContainer_H_ */
#include <asn_internal.h>
