/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/ETSI-ITS-CDD.asn"
 * 	`asn1c -no-gen-example -no-gen-BER -no-gen-APER -no-gen-OER -no-gen-JER -no-gen-random-fill -no-gen-print -fcompound-names -pdu=CAM -pdu=DENM -pdu=VAM -pdu=CollectivePerceptionMessage`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_YawRateValue_H_
#define	_YawRateValue_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum YawRateValue {
	YawRateValue_negativeOutOfRange	= -32766,
	YawRateValue_positiveOutOfRange	= 32766,
	YawRateValue_unavailable	= 32767
} e_YawRateValue;

/* YawRateValue */
typedef long	 YawRateValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_YawRateValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_YawRateValue;
asn_struct_free_f YawRateValue_free;
asn_constr_check_f YawRateValue_constraint;
xer_type_decoder_f YawRateValue_decode_xer;
xer_type_encoder_f YawRateValue_encode_xer;
per_type_decoder_f YawRateValue_decode_uper;
per_type_encoder_f YawRateValue_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _YawRateValue_H_ */
#include <asn_internal.h>
